// Module: authentication — consolidated Playwright specs (10 test cases).
// Generated by JBS IntelliQE. Tests are numbered sequentially within this file.

import { test, expect } from '@playwright/test';
import { AuthenticationPage } from '../../pages/authentication/authentication.page';

// Generated LIVE against the running application — every locator below was
// executed and verified in a real browser at generation time.
test("001 - Verify login page displays all required elements on load", async ({ page }) => {
  await page.goto("/web/index.php/auth/login");
  await expect(page.locator("img[alt='company-branding']")).toBeVisible({ timeout: 15000 });
  await expect(page.getByPlaceholder("Username")).toBeVisible({ timeout: 15000 });
  await expect(page.getByPlaceholder("Password")).toBeVisible({ timeout: 15000 });
  await expect(page.getByRole("button", { name: "Login" })).toBeVisible({ timeout: 15000 });
  await expect(page.getByText("Forgot your password?")).toBeVisible({ timeout: 15000 });
});

// Generated LIVE against the running application — every locator below was
// executed and verified in a real browser at generation time.
test("002 - Verify successful login with valid credentials redirects to Dashboard", async ({ page }) => {
  await page.goto("/web/index.php/auth/login");
  await page.getByPlaceholder("Username").fill("Admin");
  await page.getByPlaceholder("Password").fill("admin123");
  await page.getByRole("button", { name: "Login" }).click();
  await expect(page).toHaveURL(new RegExp("/dashboard/index"), { timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("/dashboard/index"), { timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("/dashboard/index"), { timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("/dashboard/index"), { timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("/dashboard/index"), { timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("/dashboard/index"), { timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("/dashboard/index"), { timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("/dashboard/index"), { timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("/dashboard/index"), { timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("/dashboard/index"), { timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("/dashboard/index"), { timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("/dashboard/index"), { timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("/dashboard/index"), { timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("/dashboard/index"), { timeout: 15000 });
});

// Generated LIVE against the running application — every locator below was
// executed and verified in a real browser at generation time.
test("003 - Verify login fails with a generic error for invalid credentials", async ({ page }) => {
  await page.goto("/web/index.php/auth/login");
  await page.getByPlaceholder("Username").fill("Admin");
  await page.getByPlaceholder("Password").fill("wrongPassword99");
  await page.getByRole("button", { name: "Login" }).click();
  await expect(page.getByText("Invalid credentials")).toContainText("", { timeout: 15000 });
  await expect(page.getByText("Invalid credentials", { exact: true })).toContainText("Invalid credentials", { timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("/web/index\\.php/auth/login"), { timeout: 15000 });
});

// Generated LIVE against the running application — every locator below was
// executed and verified in a real browser at generation time.
test("004 - Verify 'Required' validation shows for both fields when Login is clicked with empty fields", async ({ page }) => {
  await page.goto("/web/index.php/auth/login");
  await page.getByRole("button", { name: "Login" }).click();
  await expect(page.getByText("Required", { exact: true }).nth(0)).toContainText("", { timeout: 15000 });
  await expect(page.getByText("Required", { exact: true }).nth(1)).toContainText("Required", { timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("https://opensource-demo\\.orangehrmlive\\.com/web/index\\.php/auth/login"), { timeout: 15000 });
});

// Generated LIVE against the running application — every locator below was
// executed and verified in a real browser at generation time.
test("005 - Verify 'Required' validation shows for the single blank field when the other is populated", async ({ page }) => {
  await page.goto("/web/index.php/auth/login");
  await page.getByPlaceholder("Password").fill("admin123");
  await page.getByRole("button", { name: "Login" }).click();
  await expect(page.getByText("Required", { exact: true })).toBeVisible({ timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("https://opensource-demo\\.orangehrmlive\\.com/web/index\\.php/auth/login"), { timeout: 15000 });
  await page.getByPlaceholder("Password").fill("");
  await page.getByPlaceholder("Username").fill("Admin");
  await page.getByRole("button", { name: "Login" }).click();
  await expect(page.getByText("Required", { exact: true })).toBeVisible({ timeout: 15000 });
});

// Generated LIVE against the running application — every locator below was
// executed and verified in a real browser at generation time.
test("006 - Verify whitespace-only username is treated as blank after trimming", async ({ page }) => {
  await page.goto("/web/index.php/auth/login");
  await page.getByPlaceholder("Username").fill("   ");
  await page.getByPlaceholder("Password").fill("admin123");
  await page.getByRole("button", { name: "Login" }).click();
  await expect(page.getByText("Required")).toContainText("", { timeout: 15000 });
  await expect(page.getByText("Required")).toContainText("Required", { timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("/web/index\\.php/auth/login"), { timeout: 15000 });
});

// Generated LIVE against the running application — every locator below was
// executed and verified in a real browser at generation time.
test("007 - Verify password characters are masked while typing", async ({ page }) => {
  await page.goto("/web/index.php/auth/login");
  await page.getByPlaceholder("Password").fill("admin123");
  await expect(page.locator("input[name=\"password\"][type=\"password\"]")).toBeVisible({ timeout: 15000 });
});

// Generated LIVE against the running application — every locator below was
// executed and verified in a real browser at generation time.
test("008 - Verify pressing Enter submits the login form equivalent to clicking Login", async ({ page }) => {
  await page.goto("/web/index.php/auth/login");
  await page.getByPlaceholder("Username").fill("Admin");
  await page.getByPlaceholder("Password").fill("admin123");
  await page.getByPlaceholder("Password").press("Enter");
  await expect(page).toHaveURL(new RegExp("/web/index\\.php/dashboard/index"), { timeout: 15000 });
  await page.locator("span.oxd-userdropdown-tab").click();
  await page.getByText("Logout", { exact: true }).click();
  await expect(page.getByPlaceholder("Username")).toBeVisible({ timeout: 15000 });
  await page.getByPlaceholder("Username").fill("Admin");
  await page.getByPlaceholder("Password").fill("admin123");
  await page.getByPlaceholder("Username").press("Enter");
  await expect(page).toHaveURL(new RegExp("/web/index\\.php/dashboard/index"), { timeout: 15000 });
});

// Generated LIVE against the running application — every locator below was
// executed and verified in a real browser at generation time.
test("009 - Verify Enter key with empty fields triggers 'Required' validation and not a silent no-op", async ({ page }) => {
  await page.goto("/web/index.php/auth/login");
  await page.getByPlaceholder("Username").click();
  await page.getByPlaceholder("Username").press("Enter");
  await expect(page.getByText("Required", { exact: true }).nth(0)).toBeVisible({ timeout: 15000 });
  await expect(page.getByText("Required", { exact: true }).nth(1)).toBeVisible({ timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("/web/index\\.php/auth/login"), { timeout: 15000 });
  await expect(page.getByText("Required", { exact: true }).nth(0)).toBeVisible({ timeout: 15000 });
  await expect(page.getByText("Required", { exact: true }).nth(0)).toBeVisible({ timeout: 15000 });
});

test.describe('Field Validation', () => {
  test('010 - Verify leading and trailing spaces in a valid username are trimmed before authentication', async ({ page }) => {
    const login = new AuthenticationPage(page);

    // 1. Navigate to https://opensource-demo.orangehrmlive.com/web/index.php/auth/login
    // 2. Enter '  Admin  ' (with leading and trailing spaces) into the Username field
    // 3. Enter 'admin123' into the Password field
    // 4. Click the 'Login' button
    await login.login('  Admin  ', 'admin123');

    // Expected: username trimmed and user redirected to the Dashboard
    await expect(page).toHaveURL(/\/dashboard\/index/, { timeout: 15000 });
  });
});
